# Category mapping config for StayFree events
com.google.android.youtube: youtube
youtube.com: youtube
com.instagram.android: instagram
instagram.com: instagram
com.instagram.barcelona: threads
com.supercell.clashofclans: gaming
com.supercell.clashroyale: gaming
com.pubg.imobile: gaming
chatgpt.com: productivity
com.openai.chatgpt: productivity
github.com: coding
com.google.android.dialer: communication
com.google.android.gm: communication
com.google.android.googlequicksearchbox: search
in.startv.hotstar: entertainment
hotstar.onelink.me: entertainment
vlr.gg: gaming
com.snapchat.android: social
com.nothing.camera: unknown
airtribe.live: learning
withcoral.com: coding
wemakedevs.org: learning
google.com: search
mail.google.com: communication
t.co: social
twitter.com: social
com.twitter.android: social
facebook.com: social
com.facebook.katana: social
linkedin.com: productivity
com.linkedin.android: productivity
stackoverflow.com: coding
meet.google.com: communication
teams.microsoft.com: communication
zoom.us: communication
netflix.com: entertainment
spotify.com: entertainment
com.spotify.music: entertainment
amazon.in: search
amazon.com: search
primevideo.com: entertainment
